# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'

set -g mouse on
set -sg escape-time 0
set-option -sa terminal-overrides ",*256col*:Tc"
set -g default-terminal "tmux-256color"

run '~/.tmux/plugins/tpm/tpm'
set -g status-right ""
