# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "rose-pine/tmux"
set -g @rose_pine_variant "moon"

set -g mouse on
set -sg escape-time 0

set-option -sa terminal-overrides ",*256col*:Tc"

run "~/.tmux/plugins/tpm/tpm"
set -g status-right ""
