set -g mouse on
set -sg escape-time 0

set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g status-style "bg=#252530"
set -g base-index 1
set -g status-right "%H:%M %d-%b-%y"
set-window-option -g mode-keys vi
